server:
  port: 7320
  servlet:
    context-path: /api

spring:
  application:
    name: oss-statistic-service
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: SunkHikariCP
      # 配置默认数据源
      primary: statistic
      datasource:
        # 性能统计数据库
        statistic:
          username: root
          password: sunkaisens
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://mysql.com:3306/0203_statistic_service?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
        # billing写的ocr数据库 查询短信、语音、分组、组呼记录
        ocr:
          username: root
          password: sunkaisens
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://mysql.com:3306/ocr?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
        # 呈现数据库 查询0203/WJHL项目的用户入网记录
        presence:
          username: root
          password: sunkaisens
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://mysql.com:3306/presence?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
        # imserver数据库 目前用于宽带项目/0203项目查询短信信息
        imserver:
          username: root
          password: sunkaisens
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://mysql.com:3306/imserver?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
        # 资源管理数据库 目前仅用于AJU查询机动式接入记录
        resource:
          username: root
          password: sunkaisens
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://172.16.0.30:3306/2011_resource_service?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
  aop:
    proxy-target-class: true

  messages:
    basename: i18n/messages
    encoding: utf-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: redis.com
    port: 6381
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0

  mqtt: 
    enabled: true
    url: tcp://emqtt.com:1883
    clientId: Statistic@${spring.application.name}-${server.port}
    topic: /raw_alarm/#,/raw_alarm1/#,/gate_way_change
    username: admin
    password: password
    timeout: 30
    keepAlive: 60

#mybatis plus 设置
mybatis-plus:
  type-aliases-package: com.sunkaisens.ibss.statistic.model
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false

management:
  endpoints:
    web:
      exposure:
        include: '*'

ibss:
  # 是否异步记录用户操作日志
  openAopLog: true
  openAopLogGet: false
  shiro:
    # 后端免认证接口 url
    anonUrl: /**,/login,/logout/**,/regist,/user/check/**
    # token有效期，单位秒
    jwtTimeOut: 7200
    # 刷新时间检测
    refreshCheckTime: 600
  #ip转化为地域  
  ip2region:
    enabled: false

iscc:
  local:
    # 向上传输数据同步开关
    push-job-switch: false
    # 是否向上级传输数据 是-true 否-false
    upload-switch: false
    # 定时处理未同步更新数据的CRON
    push-cron: 0/5 * * * * ?
    #获取下级数据传输数据开关
    get-job-switch: false
    #获取下级数据传输数据的CRON
    get-cron: 0/5 * * * * ?
    # 本程序部署的单位ID
    unitid: 2
    # 过滤跨VCS开关
    filter-cross-vcs-switch: false
swagger:
  enable: true

# 自动创建数据表
ocr-table-create:
  enable: true
  # 创建表的的CRON
  cron: 0 0 0/23 * * ?
  # 采集OCR数据库同步性能统计数据(采集任务)
  statistic-enable: true
  # 采集任务的CRON
  statistic-cron: 0 0/15 * * * ?
  # 采集任务的周期 和CRON中的一致
  statistic-time: 15

# 语音呼叫原因值
voice:
  # 无效原因值
  invalid: [ 1,2 ]
  # 成功原因值
  success: [ 0,16,7,19,21 ]
  # 外线网关IP
  out-line-ip: [ '172.46.17.74' ]
  # 网络类型判断，0-2/3G 1-4G
  net-type:
    0: [ '192.1.1.155:9122','192.1.1.155:9132' ]
    1: [ '192.1.1.64:9904','192.1.1.64:9907' ]

#ftp配置
ftp:
  ip: 172.16.0.123
  port: 21
  username: statistic
  password: sunkaisens
  #统计信息本地路径
  temp-path: /home/sun-nms/statistic/local
  #统计信息下级同步上来的数据路径
  path: /home/sun-nms/statistic


snmp:
  # 是否开启snmp获取分组流量逻辑
  flag: false
  # 本机IP
  localAddress: 192.168.1.101
  # 单位 秒
  period: 60
  # 天通网系对应交换机IP及网口
  dataGateWayIp[1]: 192.168.1.31
  netPort[1]: 1,2,3,4
  nets[1]: 天通移动通信网
  # FDMA网系对应换机IP及网口
  dataGateWayIp[3]: 192.168.1.31
  netPort[3]: 5,6,7,8
  nets[3]: FDMA综合业务网
  # FDMA网系对应换机IP及网口
  dataGateWayIp[4]: 192.168.1.31
  netPort[4]: 9,10,11,12
  nets[4]: TDMA综合业务网
  # FDMA网系对应换机IP及网口
  dataGateWayIp[5]: 192.168.1.31
  netPort[5]: 13,14,15,16
  nets[5]: TDMA综合业务网及升级
  # FDMA网系对应换机IP及网口
  dataGateWayIp[10]: 192.168.1.31
  netPort[10]: 17,18,19,20
  nets[10]: 网间互联SIP
  # FDMA网系对应换机IP及网口
  dataGateWayIp[11]: 192.168.1.31
  netPort[11]: 21,22,23,24
  nets[11]: 网间互联固话
  # FDMA网系对应换机IP及网口
  dataGateWayIp[12]: 192.168.1.31
  netPort[12]: 25,26,27,28
  nets[12]: UHF战术/手持通信网
  # FDMA网系对应换机IP及网口
  dataGateWayIp[13]: 192.168.1.31
  netPort[13]: 29,30,31,32
  nets[13]: UHF频段通信网

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka.com:7000/eureka/,http://eureka.com:7001/eureka/
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: statistic-service
  company.name: www.sunkaisense.com

feign-service:
  log: hlht-security-service
  user: oss-user-service
  organization: hlht-organization-service

logging:
  config: classpath:log4j2-spring.xml


       
