server:
  port: 7335
  servlet:
    context-path: /api
  
spring:
  application:
    name: oss-gmapsystem-service
  autoconfigure: #排除原生Druid的快速配置类。
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: SunkHikariCP
      # 配置默认数据源
      primary: primary
      datasource:
        # 数据源-1，名称为 primary
        primary:
          username: root
          password: sunkaisens
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://mysql.com:3306/0203_gmapsystem_service?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
  aop:
    proxy-target-class: true

  messages:
    encoding: utf-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: redis.com
    port: 6381
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0


#activemq的配置
  activemq:
    broker-url: tcp://activemq.com:61616
    user: admin
    password: admin
    close-timeout: 15s   # 在考虑结束之前等待的时间
    in-memory: true      # 默认代理URL是否应该在内存中。如果指定了显式代理，则忽略此值。
    non-blocking-redelivery: false  # 是否在回滚回滚消息之前停止消息传递。这意味着当启用此命令时，消息顺序不会被保留。
    send-timeout: 0     # 等待消息发送响应的时间。设置为0等待永远。
    queue-name: event
    topic-name: event
#    packages:
#      trust-all: true #不配置此项，会报错
    pool:
     enabled: true
     max-connections: 10   #连接池最大连接数
     idle-timeout: 30000   #空闲的连接过期时间，默认为30秒

#    jms:
#      pub-sub-domain: true  #默认为false，即queue模式，若要使用topic模式需要配置为true，


#mybatis plus 设置
mybatis-plus:
  type-aliases-package: com.sunkaisens.ibss.gmapsystem.domain
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
     health:
        show-details: ALWAYS

ibss:
  # 是否异步记录用户操作日志
  openAopLog: true
  shiro:
    # 后端免认证接口 url
    anonUrl: /login,/logout/**,/regist,/user/check/**
    # token有效期，单位秒
    jwtTimeOut: 7200
    # 刷新时间检测
    refreshCheckTime: 600 
  #ip转化为地域  
  ip2region:
    enabled: false
  # 单次最大批量入库数量
  max:
    batch:
      insert:
        num: 1000
swagger:
  enable: true 
   
info: 
  app.name: ${spring.application.name}
  company.name: www.sunkaisense.com

pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

iscc:
  group:
    enabled: true
    ip: group.com
    port: 1000
    groupType: public-group
    assertedIdentity: sip:administrator@test.com
      
ribbon:
  eureka:
    enabled: true

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://eureka.com:7000/eureka/,http://eureka.com:7001/eureka/   
  instance:
    #ip-address: oss.com
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址
    health-check-url-path: ${server.servlet.context-path}/actuator/health

feign-service:
  log: oss-security-service
  user: oss-user-service
  resource: oss-resource-service
  antijam-1: antijam-1
  antijam-2: antijam-2
  antijam-3: antijam-3
 
#读取波束的文件  xsh  2020/6/3
banddata:
  filePath: /home/sun-nms/gmap/band/band_ellipse_data.txt
  filePath2: /home/sun-nms/gmap/band/band_ellipse_data2.txt
  filePath3: /home/sun-nms/gmap/band/band_ellipse_data3.txt
  satellite_conf: 2 #查询抗干扰波束，2代表2星


#mqtt 的路径  xsh  2020/6/3
mqtt:
  ip: emqtt.com
  port: 1883
  updatedbTime: 30
  emrgCenterMdn: 18980020200

#mqsend的地址
mqttsend: 
  ip: emqtt.com
  port: 1883
  
#地图地址   xsh  2020/6/3
roadmap:
   ip: map.com
   port: 8898

logging:
  config: log4j2-spring.xml

