server:
  port: 6002
  servlet:
    context-path:
    #security:
    #  basic:
    #    enabled: true
    #    path: /swagger-ui.html
    #  user:
    #    name: admin
    #    password: admin

spring:
  application:
    name: oss-organization-service
  autoconfigure: #排除原生Druid的快速配置类。
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: SunkHikariCP
      # 配置默认数据源
      primary: primary
      datasource:
        # 数据源-1，名称为 primary
        primary:
          username: root
          password: sunkaisens
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://mysql.com:3306/0203_organization_service?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
        # 数据源-2，名称为 test
  #        test:
  #          username: root
  #          password: 123456
  #          driver-class-name: com.mysql.cj.jdbc.Driver
  #          url: jdbc:mysql://127.0.0.1:3306/febs_test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  aop:
    proxy-target-class: true

  messages:
    encoding: utf-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: redis.com
    port: 6381
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0
feign:
  hystrix:
    enabled: true


#mybatis plus 设置
mybatis-plus:
  type-aliases-package: com.sunkaisens.ibss.system.domain,com.sunkaisens.ibss.organization.domain
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false

pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

ibss:
  # 是否异步记录用户操作日志
  openAopLog: true
  openAopLogGet: false
  shiro:
    # 后端免认证接口 url
    anonUrl: /login,/logout/**,/regist,/user/check/**,/unit/share/**
    # token有效期，单位秒
    jwtTimeOut: 7200
    # 刷新时间检测
    refreshCheckTime: 600
  #ip转化为地域
  ip2region:
    enabled: false
  # 单次最大批量入库数量
  max:
    batch:
      insert:
        num: 1000
swagger:
  enable: true

info:
  app.name: ${spring.application.name}
  company.name: www.sunkaisense.com

iscc:
  group:
    enabled: false   #访问群组的开关
    ip: 192.168.3.200
    port: 1000
    groupType: public-group
    assertedIdentity: sip:administrator@test.com
  synchronized:
    # 本程序是否为顶级，此选项仅影响添加单位时的默认单位类型，true-分级单位和分域单位可选 false-分域单位
    data-center: true
    # 是否向上级同步
    enabled: false
    # 上级单位组织架构IP
    ip: 172.16.0.30
    # 上级单位组织架构PORT
    port: 6002
    # 向上级单位请求本单位的级单位信息
    level-cron: 0 */30 * * * ?
    # 向上级单位推送更新本单位的域单位信息
    domain-merge-cron: 0 */30 * * * ?
    # 向上级单位推送删除本单位的域单位信息
    domain-delete-cron: 0 */30 * * * ?
    # 本地单位ID
    unit-id: 0
    # 删除修改单位是否检测单位可否操作
    del-upt-check-unit: false

ribbon:
  eureka:
    enabled: true

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka.com:7000/eureka/,http://eureka.com:7001/eureka/
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址
    health-check-url-path: ${server.servlet.context-path}/actuator/health


feign-service:
  log: oss-security-service
  user: oss-user-service
  resource: oss-resource-service

logging:
  config: log4j2-spring.xml

