server:
  port: 7330
  servlet:
    context-path:

# omc 项目的路径 xsh 2020/1/11
spring:
  application:
    name: oss-user-service
  autoconfigure: #排除原生Druid的快速配置类。
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      druid: #以下是全局默认值，可以全局更改
        initial-size: 0
        max-active: 8
        min-idle: 2
        max-wait: -1
        min-evictable-idle-time-millis: 30000
        max-evictable-idle-time-millis: 30000
        time-between-eviction-runs-millis: 0
        validation-query: select 1
        validation-query-timeout: -1
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        pool-prepared-statements: true
        max-open-prepared-statements: 100
        filters: stat
        share-prepared-statements: true
      # 配置默认数据源
      primary: primary
      datasource:
        # 数据源-1，名称为 primary
        primary:
          username: root
          password: sunkaisens
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://mysql.com:3306/0203_user_service?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
  aop:
    proxy-target-class: true

  messages:
    basename: i18n/messages
    encoding: utf-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: redis.com
    port: 6381
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0

  # 本地MQTT连接信息
  mqtt-local:
    enabled: true
    url: tcp://emqtt.com:1883
    clientId: ${spring.application.name}-${server.port}
    topic: Presence/Register/#
    topic-send: /oss-user-to-front
    username: admin
    password: password
    timeout: 30
    keepAlive: 60
  # 上级MQTT连接信息
  mqtt-boss:
    enabled: false
    url: tcp://emqttboss.com:1883
    clientId: ${spring.application.name}-${server.port}-Subordinate
    topic: down/user/swoon,down/user/restore,down/user/destroy,down/user/normal
    timeout: 30
    keepAlive: 60

#mybatis plus 设置
mybatis-plus:
  type-aliases-package: com.sunkaisens.ibss.system.domain,com.sunkaisens.ibss.user.model
  #配置要扫描的Xml的文件 即sql文件
  mapper-locations: classpath:mapper/*/*.xml,classpath:mapper/*/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

ibss:
  # 是否异步记录用户操作日志
  openAopLog: false
  openAopLogGet: false
  shiro:
    # 后端免认证接口 url
    anonUrl: /api/user/check/**,/api/hss/share/**,/api/hss/tt-user,/api/oss-user-service/user/check/**,/api/oss-user-service/hss/share/**,/api/oss-user-service/hss/tt-users
    # token有效期，2个小时     两个小时如果不操作 会退出。单位 秒
    jwtTimeOut: 7200
    # 更新令牌时间检查配置，10分钟刷新一次     单位 ：秒
    refreshCheckTime: 600
  #ip转化为地域  
  ip2region:
    enabled: false
  # 单次最大批量入库数量
  max:
    batch:
      # 单次最大新增数量
      insert-num: 1000
      # 单次最大删除数量
      delete-num: 1000
  # RestTemplate的超时配置
  rest-http:
    # 连接超时时间：单位 毫秒
    connect-timeout: 120000
    # 读取超时时间：单位 毫秒
    read-timeout: 60000

swagger:
  enable: true

info:
  app.name: ${spring.application.name}
  company.name: www.sunkaisense.com

iscc:
  group:
    enabled: false
    ip: group.com
    port: 1000
    groupType: public-group
    assertedIdentity: sip:administrator@test.com
  # 缓存IMSI MDN STATUS
  cache:
    # 缓存项最大数量
    size: 100000
    # 缓存时间：天
    duration: 10
  # 同步配置
  synchronized:
    # 是否向上级同步数据
    enabled: false
    # 上级用户管理IP
    ip: datacenter.com
    # 上级用户管理PORT
    port: 7330
  local:
    # 定时处理未同步更新数据的CRON
    merge-cron: 0 */30 * * * ?
    # 获取未同步数据的分页的每页数据量大小
    merge-page-size: 500
    # 定时处理未同步删除数据的CRON
    delete-cron: 0 */30 * * * ?
    # 本程序部署的单位ID
    unitid: 0
    # 用户变更时是否使用该默认单位ID true:适用于2011 false:适用于0203
    # 使用默认单位ID-true，前端传输单位ID-false
    enable: false
    priority: true
  hss:
    # 批量添加操作是否开启线程执行
    batch-add-thread-switch: false
    # 批量删除操作是否开启线程执行
    batch-delete-thread-switch: false
    # TerminalInfo表写入开关
    terminalInfo-switch: true
    # EpcData和EpcTft表写入开关
    roaming-pdt-switch: false
    epc-switch: false
    # EpcData和EpcTft表写入类型 LTE-TD(5) LTE-CPE(13)
    epc-device-type:  5,13 
    # 批量添加用户时displayName字段截取规则
    batch-add-displayName-length: 8
    # 批量修改，忽略AUC鉴权参数修改的设备类型
    batch-update-ignore-auc-device-type:  0 
  net-policy:
    # 特殊网系规则配置（内容为：MDN前缀|网系ID|HSS代理模块ID）
    special-rules: 174|1|1,184|2|1 

aju-jds:
  port: 7350    

auc-usim:
  enable: false
  url: http://10.0.30.104:8080/USIM_Manage30
  detect-cron: 0 */3 * * * ?
  # HSS-PROXY程序ID,AUC设备编号
  aucNo: 1:202012254668,2:202012254662,3:202012254663,4:202012254664

oam: 
  local:
    ip: 172.16.0.28
    port: 12500
  remote:
    ip: 172.16.0.38
    port: 9999
  status: 
    send: true
    period: 60
#canal 配置
ali:
  canal:
    switch: false
    addr: canal.com
    port: 11111
    #      注意：带特殊字符的配置文件必须加双引号，否则会解析有误
    # tablesubscribe: "hss\\..*"
    tablesubscribe: "hss.HLR"
    destinations: omc-user
    user: root
    password: root

ribbon:
  eureka:
    enabled: true

pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka.com:7000/eureka/,http://eureka.com:7001/eureka/
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址    
    health-check-url-path: ${server.servlet.context-path}/actuator/health

feign-service:
  log: oss-security-service
  organization: oss-organization-service
  appear: https://172.16.0.174:8080/regsiter/status
logging:
  config: log4j2-spring.xml

