server:
  port: resource_local_port

use:
  viewLog: false
            
resource-management:
  url: http://nmsDomainName:1025/devType

organization-management:
  url: http://nmsDomainName:9527/unit/unitListAll
  
devTypePicture:
  path: C:/other/Web_NMS/resource-management/static/

jizhan:
  id: 1
  
alarmHistoryLog:
  deleteMonth: 6

feign-service: 
  log: eurekaSecurityServiceName
  resource: eurekaResourceServiceName
  alarm: eurekaAlarmServiceName
  devconfig: eurekaDevconfigServiceName
    
spring:
  # zipkin: 
    # base-url: http://nmsDomainHost:8769
  application:
    name: eurekaResourceServiceName
  autoconfigure: #排除原生Druid的快速配置类。
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    #type: com.alibaba.druid.pool.DruidDataSource
    #druid:
      #connectionErrorRetryAttempts: 0
      #breakAfterAcquireFailure: true
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: SunkHikariCP
      # 配置默认数据源
      primary: devconfig
      datasource:
        # 数据源-1，名称为 primary
        alarm:
          username: softwareDbUsername
          password: softwareDbpassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localMysqlDomainName:3306/alarmDbName?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
        resource:
          username: softwareDbUsername
          password: softwareDbpassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localMysqlDomainName:3306/resourceDbName?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
        devconfig:
          username: softwareDbUsername
          password: softwareDbpassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localMysqlDomainName:3306/devconfigNameDbName?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowMultiQueries=true&useSSL=false
  aop:
    proxy-target-class: true
  messages:
    encoding: utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: redisDomainName
    port: redisPort
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 2000
        max-active: 5000
        max-wait: 10000
    timeout: 0
  mqtt:
    enabled: true
    url: "tcp://mqttDomainName:mqttPort"
    clientId: ${spring.application.name}39
    topic: /raw_alarm/#,/raw_alarm1/#
    OamTopic: "$share/1808/alarm-service/alarm,$share/1808/bridge/2011/alarm-service/alarm_bridge,$share/1808/resource-service/status_alarm,$share/1808/resource-service/status_oam,$share/1808/bridge/2011/resource-service/status_oam_bridge,$share/1808/bridge/2011/rru_status_bridge,$share/1808/bridge/2011/link_status_bridge,$share/1808/bridge/2011/comment_link_bridge,$share/1808/bridge/2011/resource-service/status_alarm_bridge,$share/1808/bridge/2011/event_bridge"
    bridgeTopic: "alarm-service/alarm_bridge"
    alarmFrontTopic: "front-service/alarm"
    alarmTopologyTopic: "topology-service/alarm"
    resourceTopic: "resource-service/status_alarm"
    logTopic: "security/addlogs"
    BBUTopic: "bbu_select"
    RRUTopic: "rru_status"
    LinkStatus: "link_status"
    CommentLink: "comment_link"
    event: "event"
    bbuOnline: "bbu_online"
    bridgeEvent: "event_bridge"
    bridgeRRUTopic: "rru_status_bridge"
    bridgeLinkStatus: "link_status_bridge"
    bridgeCommentLink: "comment_link_bridge"
    bridgeOamTopic: "resource-service/status_oam_bridge"
    bridgeStatusAlarmTopic: "resource-service/status_alarm_bridge"
    resourceFrontTopic: "front-service/status"
    FrontLinkTopic: "front-service/link"
    FrontEventTopic: "front-service/event"
    resourceTopologyTopic: "topology-service/status"
    updateBtsName: "update_bts_name"
    username: admin
    password: password
    timeout: 30
    keepAlive: 60

#mybatis plus 设置
mybatis-plus:
  type-aliases-package: com.sunkaisens.ibss.alarm.model.entity
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: ALWAYS
      shutdown:
        enabled: true
        
ibss:
  # 是否异步记录用户操作日志
  openAopLog: true
  openAopLogGet: false
  shiro:
    # 后端免认证接口 url
    anonUrl: /login,/logout/**,/regist,/user/check/**
    # token有效期，单位秒
    jwtTimeOut: 7200
    # 更新令牌时间检查配置，10分钟刷新一次     单位 ：秒
    refreshCheckTime: 600
  ip2region:
    enabled: false
  # 基站心跳消息相关配置
  btsHeartBeat:
    # 是否开启此定时器
    enable: true
    # 未收到基站心跳消息后发送告警的超时时间，单位：秒
    duration: 60
    # 基站心跳消息检测cron
    cron: 0 */2 * * * ?

  udp:
    comm:
      btsPort: 9183
      btsTimeout: 3000
      oamPort: 9922
      oamTimeout: 3000

  bts:
    pdt:
      send-base-freq: 358000000
      receive-base-freq: 348000000
      freq-step: 12500
    mdt:
      send-base-freq: 386012500
      receive-base-freq: 376012500
      freq-step: 25000
  # 单次最大批量入库数量
  max:
    batch:
      insert:
        num: 1000
        
#配置pageHelper分页插件
pagehelper:
  helper-dialect: mysql #指定数据库类型（mysql、oracle）
  reasonable: true #启用合理化，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  support-methods-arguments: true #支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页
  params: count=countSql #指定pageHelper统计某张表中的总记录数
  page-size-zero: true #如果 pageSize=0 就会查询出全部的结果（相当于没有执行分页查询）
      
eureka:
  client: #客户端注册进eureka服务列表内
    enabled: true
    service-url: 
       defaultZone: http://microDomainName:microPort7000/eureka/,http://microDomainName:microPort7001/eureka/      
  instance:
    #ip-address: 172.16.0.145
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址     

feign:
  hystrix:
    enabled: true
    
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

info: 
  app.name: ${spring.application.name}
  company.name: www.sunkaisense.com
  
logging: 
  config: log4j2-spring.xml

alarm:
 #是否同步
 open: false
 #本级ip
 ip: nmsDomainName
 #本级port
 port: alarmLocalPort
 #上级层级
 level: superior_nms_level
 #数据中心url
 synchronized: http://datacenterDomainName:datacenter_port/v1/nms-alarm-service/
 #是否是数据中心
 dataCenter: false
 #设备来源
 source: dev_srouce_from_name

 
dev:
 #是否开启设备上报
 open: false
 #本级网管ip
 ip: nmsDomainName
 #本级网管port
 port: nms_login_port
 #上级网管url
 synchronized: http://datacenterDomainName:datacenter_port/v1/nms-resource-service
 #设备来源
 source: dev_srouce_from_name
 # 增加设备同步配置
 devTimer: "0 0/3 * * * ?"
 
 
#数据中心同步定时任务
cron:
 timer: "0 0 0 * * ?"
 alarmWarehouseTimer: "0 0 0 * * ?"
 alarmTimer: "0 0 0 * * ?"
 devTimer: "0 0/3 * * * ?"
 
udp:
  localIp: nmsDomainName
  localPort: resource_alarm_local_udp_port
  isSoBroadcast: false
  timeoutTime: 40000 
 
#地图纠偏  true代表纠偏  false代表不纠偏
mapRectification:
  open: false

