server:
  port: north_local_port
  servlet:
    context-path: /api/nms-ni-service


spring:
  application:
    name: eurekaNorthServiceName
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      druid: #以下是全局默认值，可以全局更改
        initial-size: 0
        max-active: 8
        min-idle: 2
        max-wait: -1
        min-evictable-idle-time-millis: 30000
        max-evictable-idle-time-millis: 30000
        time-between-eviction-runs-millis: 0
        validation-query: select 1
        validation-query-timeout: -1
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        pool-prepared-statements: true
        max-open-prepared-statements: 100
        filters: stat,wall
        share-prepared-statements: true
      # 配置默认数据源
      primary: primary
      datasource:
        # 数据源-1，名称为 primary
        primary:
          username: softwareDbUsername
          password: softwareDbpassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localMysqlDomainName:3306/northDbName?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
        hss:
          username: softwareDbUsername
          password: softwareDbpassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://switchIp:3306/hssDbName?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useSSL=false
        presence:
          username: softwareDbUsername
          password: softwareDbpassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://dispIp:3306/presenceDbName?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useSSL=false
        myomc:
          username: softwareDbUsername
          password: softwareDbpassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localMysqlDomainName:3306/myomcDbName?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useSSL=false
        ocr:
          username: softwareDbUsername
          password: softwareDbpassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localMysqlDomainName:3306/ocrDbName?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&useSSL=false


  aop:
    proxy-target-class: true

  messages:
    basename: i18n/messages
    encoding: utf-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: redisDomainName
    port: redisPort
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0

  mqtt-local:
    enabled: true
    url: tcp://mqttDomainName:mqttPort
    clientId: ${spring.application.name}-${server.port}
    topic: notice,north/status/#,north/alarm/#,front-service/status
    topic-send: /0203-user-to-front
    username: admin
    password: password
    timeout: 30
    keepAlive: 60

#mybatis plus 设置
mybatis-plus:
  type-aliases-package: com.sunkaisens.system.domain,com.sunkaisens.north.model
  #配置要扫描的Xml的文件 即sql文件
  mapper-locations: classpath:mapper/*/*.xml,classpath:mapper/*/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

ibss:
  # 是否异步记录用户操作日志
  openAopLog: true
  openAopLogGet: false
  #ip转化为地域
  ip2region:
    enabled: false
  # RestTemplate的超时配置
  rest-http:
    # 连接超时时间：单位 毫秒
    connect-timeout: 120000
    # 读取超时时间：单位 毫秒
    read-timeout: 60000

user:
  mdn-prefix: "4600"

#站点port配置信息
station:
  enable: false
  deviceMap[01]: 7305
  deviceMap[02]: 7305
  alarmMap[01]: 7310
  alarmMap[02]: 7310

udp:
  # 发送oam的UDP消息的延时时间(ms)
  sendDelay: 50
  # 发送oam的UDP消息的超时时间(s)
  timeout: 5


north:
  nms:
    enable: true
    local-ip: nmsDomainName
    local-port: northLocalPort
    remote-ip: north2OtherNmsDomainName
    remote-port: north2OtherNmsPort
    report-cron: 0/10 * * * * ?

oam:
  ip: oam_local_domainname
  port: 6225
  net-e1[15]: 256-1
  net-e1[17]: 256-1

jds:
  # 机动式IP
  ip: 10.106.0.194
  # 机动式是否向AJ网管推送任务和位置信息
  loc-task-enable: false
  # 机动式向AJ网管推送位置的CRON
  location-cron: 0/30 * * * * ?
  # 机动式向AJ网管推送任务的CRON
  dev-task-cron: 0/10 * * * * ?
  # 机动式是否向AJ网管同步性能统计数据(采集任务)
  statistic-enable: false
  # 网络类型判断，0-2/3G 1-4G
  net-type:
    0: [ '192.1.1.155:9122','192.1.1.155:9132' ]
    1: [ '192.1.1.64:9904','192.1.1.64:9907' ]

swagger:
  enable: true

info:
  app.name: ${spring.application.name}
  company.name: www.sunkaisense.com

ribbon:
  ReadTimeout: 10000
  ##建立连接后从服务器读取到可用资源所用的时间,默认1秒,这里配置10秒
  ConnectTimeout: 10000
  eureka:
    enabled: false

#eureka:
#  client: #客户端注册进eureka服务列表内
#    service-url:
#      defaultZone: http://172.16.0.123:7000/eureka/
#  instance:
#    instance-id: ${spring.application.name}-${server.port}
#    prefer-ip-address: true     #访问路径可以显示IP地址

feign-service:
  log: http://nmsDomainName:nmsLogPort
  user: http://nmsDomainName:nmsUserPort
  device: http://nmsDomainName:nmsDevicePort
  statistic: http://nmsDomainName:nmsStatisticPort
  monitor: http://nmsDomainName:nmsMonitorPort
  organization: http://nmsDomainName:nmsOrganizationPort

logging:
  config: classpath:log4j2-spring.xml


