server:
  port: devconfig_local_port
  #servlet:
    #context-path: /1808-devconfig-service

spring:
  application:
    name: eurekaDevconfigServiceName
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: SunkHikariCP
      # 配置默认数据源
      primary: primary
      datasource:
        # 数据源-1，名称为 primary
        primary:
          username: softwareDbUsername
          password: softwareDbpassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://mysql.com:3306/devconfig_dbname?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowMultiQueries=true
        # 数据源-2，名称为 test
#        omc:
#          username: softwareDbUsername
#          password: softwareDbpassword
#          driver-class-name: com.mysql.jdbc.Driver
#          url: jdbc:mysql://nms_domainName:3306/myomc_dbname?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  aop:
    proxy-target-class: true

  messages:
    encoding: utf-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: redis_domainName
    port: redis_port
    password: 
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0

  mqtt: 
    enabled: true
    url: tcp://mqtt_domainName:mqtt_port
    clientId: Devconfig@Chris
    topic: /raw_alarm/#,/raw_alarm1/#
    username: admin
    password: password
    timeout: 30
    keepAlive: 60
    sendPeriod: 40000
    sendBtsStatusTopic: resource-service/status_oam
    sendBtsAlarmTopic: alarm-service/alarm
    btsRruStatusTopic: rru_status
    btsLinkStatusTopic: link_status
    btsEventTopic: event


#mybatis plus 设置
mybatis-plus:
  type-aliases-package: com.sunkaisens.ibss.module.domain
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false

management:
  endpoints:
    web:
      exposure:
        include: ['httptrace', 'metrics']

ibss:
  # 是否异步记录用户操作日志
  openAopLog: true
  openAopLogGet: false
  shiro:
    # 后端免认证接口 url
    anonUrl: /**,/login,/logout/**,/regist,/user/check/**
    # token有效期，单位秒
    jwtTimeOut: 7200
    # 刷新时间检测
    refreshCheckTime: 600
  #ip转化为地域  
  ip2region:
    enabled: false
  # 基站心跳消息相关配置
  btsHeartBeat:
    # 是否开启此定时器
    enable: true
    # 未收到基站心跳消息后发送告警的超时时间，单位：秒
    duration: 60
    # 基站心跳消息检测cron
    cron: 0 */2 * * * ?
  # 单次最大批量入库数量
  max:
    batch:
      insert:
        num: 1000
  udp:
    comm:
      btsPort: devconfig_bts_port
      btsTimeout: 10000
      oamPort: devconfig_oam_bts_port
      oamTimeout: 3000
      
  oam:
    oamIP: oam_local_ip
    oamPort: oam_local_port
  bts:
    pdt:
      send-base-freq: 358000000
      receive-base-freq: 348000000
      freq-step: 12500
    mdt:
      send-base-freq: 386012500
      receive-base-freq: 376012500
      freq-step: 25000    

swagger:
  enable: true
  
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://micro_domainName:micro_port7000/eureka/,http://micro_domainName:micro_port7001/eureka/
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址     
    
logging:
 # config: classpath:log4j2-spring.xml
  config: log4j2-spring.xml
info: 
  app.name: eurekaDevconfigServiceName
  company.name: www.sunkaisense.com 

feign-service: 
  log: eurekaDevconfigServiceName
  zkMonitor: fh03-zkmonitor-service
feign:
  hystrix:
    enabled: true
