server:
  port: 7310
  servlet:
    context-path: /api
           
resource-management:
  url: http://nms_ip:1025/devType
  
alarmHistoryLog:
  deleteMonth: 6

feign-service: 
  log: eurekaSecurityServiceName
  resource: eurekaResourceServiceName
  alarm: eurekaAlarmServiceName

spring:
  # zipkin: 
    # base-url: http://192.168.3.61:8769
  application:
    name: aj03-alarm-service
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: SunkHikariCP
      # 配置默认数据源
      primary: primary
      datasource:
        # 数据源-1，名称为 primary
        primary:
          username: software_db_username
          password: software_db_password
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://nms_domain:mysql_port/alarm_dbname?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
  aop:
    proxy-target-class: true
  messages:
    encoding: utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: redis_domain
    port: redis_port
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0
  mqtt-local:
    enabled: true
    url: "tcp://mqtt_domain:mqtt_port"
    clientIdPrefix: ${spring.application.name}-local
    OamTopic: "alarm-service/alarm"
    FrontTopic: "front-service/alarm"
    TopologyTopic: "topology-service/alarm"
    resourceTopic: "resource-service/status_alarm"
    username: admin
    password: password
    timeout: 30
    keepAlive: 60
  mqtt-ni:
    enabled: true
    url: "tcp://Up_Mqtt_Ip:mqtt_port"
    clientIdPrefix: ${spring.application.name}-ni
    #注意/1/2代表站点
    NiTopic: "north/alarm/1"
    username: admin
    password: password
    timeout: 30
    keepAlive: 60

#mybatis plus 设置
mybatis-plus:
  type-aliases-package: com.sunkaisens.ibss.alarm.model.entity
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false
    
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: ALWAYS
      shutdown:
        enabled: true
        
ibss:
  # 是否异步记录用户操作日志
  openAopLog: true
  shiro:
    # 后端免认证接口 url
    anonUrl: /login,/logout/**,/regist,/user/check/**
    # token有效期，单位秒
    jwtTimeOut: 7200
    # 更新令牌时间检查配置，10分钟刷新一次     单位 ：秒
    refreshCheckTime: 600
  ip2region:
    enabled: false
  # 单次最大批量入库数量
  max:
    batch:
      insert:
        num: 1000
        
#配置pageHelper分页插件
pagehelper:
  helper-dialect: mysql #指定数据库类型（mysql、oracle）
  reasonable: true #启用合理化，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  support-methods-arguments: true #支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页
  params: count=countSql #指定pageHelper统计某张表中的总记录数
  page-size-zero: true #如果 pageSize=0 就会查询出全部的结果（相当于没有执行分页查询）
      
eureka:
  client: #客户端注册进eureka服务列表内
    enabled: true
    service-url: 
       defaultZone: http://eureka_domain:micro_port1/eureka/,http://eureka_domain:micro_port2/eureka/     
  instance:
    #ip-address: 172.16.0.220
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址     

feign:
  hystrix:
    enabled: false

info: 
  app.name: ${spring.application.name}
  company.name: www.sunkaisense.com
  
logging: 
  config: log4j2-spring.xml

switch:
  aj: true

ftp:
 pingTime: 2000
 intervalTime: 1000
