server:
  port: statistic_port
  servlet: 
    context-path: /api
            
spring:
  application:
    name: eurekaStatisticServiceName
  cloud: 
    config: 
      profile: wideBand
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: SunkHikariCP
      # 配置默认数据源
      primary: primary
      datasource:
        # billing写的ocr数据库 查询短信、语音、分组、组呼记录
        primary:
          username: software_db_username
          password: software_db_password
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://nms_domain:mysql_port/ocr_dbname?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
        # 呈现数据库 查询0203/WJHL项目的用户入网记录
        presence:
          username: software_db_username
          password: software_db_password
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://disp_domain:mysql_port/presence_dbname?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
        # imserver数据库 目前用于宽带项目/0203项目查询短信信息
        imserver:
          username: software_db_username
          password: software_db_password
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://disp_domain:mysql_port/imserver_dbname?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
        # 资源管理数据库 目前仅用于AJU查询机动式接入记录
        resource:
          username: software_db_username
          password: software_db_password
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://nms_domain:mysql_port/resource_dbname?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
        # 性能统计数据库 目前仅用于WJHL项目的SNMP获取分组数据后存储及查看
        statistic:
          username: software_db_username
          password: software_db_password
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://nms_domain:mysql_port/statistic_dbname?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
  aop: 
    proxy-target-class: true
  messages:
    basename: i18n/messages
    encoding: utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis: 
    host: redis_domain
    port: redis_port
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0
  mqtt:
      enabled: false
      url: tcp://mqtt_domain:mqtt_port
      clientId: Statistic@${spring.application.name}-${server.port}
      topic: /raw_alarm/#,/raw_alarm1/#
      username: admin
      password: password
      timeout: 30
      keepAlive: 60

#mybatis plus 设置
mybatis-plus:
  type-aliases-package: com.sunkaisens.ibss.statistic.model
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false

management:
  endpoints:
    web:
      exposure:
        include: '*'

ibss:
  # 是否异步记录用户操作日志
  openAopLog: true
  openAopLogGet: false
  shiro:
    # 后端免认证接口 url
    anonUrl: /login,/logout/**,/regist,/user/check/**
    # token有效期，单位秒
    jwtTimeOut: 3600
    # 更新令牌时间检查配置，10分钟刷新一次     单位 ：秒
    refreshCheckTime: 600
  #ip转化为地域  
  ip2region:
    enabled: false

swagger:
  enable: true
 
#canal 配置
ali:
  canal:
    flag: false
    addr: canal.com
    port: 11111
#   注意：带特殊字符的配置文件必须加双引号，否则会解析有误
    tablesubscribe: "ocr\\..*"
    user: root
    password: root
    hostName: statistic

logging:
  config: log4j2-spring.xml

feign-service: 
  log: eurekaSecurityServiceName
  user: eurekaUserServiceName
  gmap: aj03-gmapsystem-service

eureka: 
  client: #客户端注册进eureka服务列表内
    service-url: 
       defaultZone: http://micro_domain:micro_port1/eureka/,http://micro_domain:micro_port2/eureka/
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址     
 
info: 
  app.name: ${spring.application.name}
  company.name: www.sunkaisense.com 

# 从redis获取IP和设备映射关系，目前只支持WJHL、AJU
ip-dev-relation: true

# 从态势存储的redis信息中获取终端注册网关信息 识别是哪颗卫星、接入模式（常规、抗干扰、应急）和业务类型（语音、短信）
satellite: false

ocr-table-create:
  enable: true
  cron: 0 0 23 * * ?
  #cron: 0 */1 * * * ?

# 语音呼叫原因值
voice:
  # 无效原因值
  invalid: [ 1,2 ]
  # 成功原因值
  success: [ 0,16,7,18,21 ]
  # 外线网关IP
  out-line-ip: [ '172.46.17.74' ]

snmp:
  # 是否开启snmp获取分组流量逻辑
  flag: false
  # 本机IP
  localAddress: 192.168.1.101
  # 单位 秒
  period: 60
  # 天通网系对应交换机IP及网口
  dataGateWayIp[1]: 192.168.1.31
  netPort[1]: 1,2,3,4
  nets[1]: 天通移动通信网
  # FDMA网系对应换机IP及网口
  dataGateWayIp[3]: 192.168.1.31
  netPort[3]: 5,6,7,8
  nets[3]: FDMA综合业务网
  # FDMA网系对应换机IP及网口
  dataGateWayIp[4]: 192.168.1.31
  netPort[4]: 9,10,11,12
  nets[4]: TDMA综合业务网
  # FDMA网系对应换机IP及网口
  dataGateWayIp[5]: 192.168.1.31
  netPort[5]: 13,14,15,16
  nets[5]: TDMA综合业务网及升级
  # FDMA网系对应换机IP及网口
  dataGateWayIp[10]: 192.168.1.31
  netPort[10]: 17,18,19,20
  nets[10]: 网间互联SIP
  # FDMA网系对应换机IP及网口
  dataGateWayIp[11]: 192.168.1.31
  netPort[11]: 21,22,23,24
  nets[11]: 网间互联固话
  # FDMA网系对应换机IP及网口
  dataGateWayIp[12]: 192.168.1.31
  netPort[12]: 25,26,27,28
  nets[12]: UHF战术/手持通信网
  # FDMA网系对应换机IP及网口
  dataGateWayIp[13]: 192.168.1.31
  netPort[13]: 29,30,31,32
  nets[13]: UHF频段通信网


