#   : 号和 数值之间要有空格 如： port: 9527
server:
  port: security_port
#security:
#  basic:
#    enabled: true
#    path: /swagger-ui.html
#  user:
#    name: admin
#    password: admin

use:  
  viewLog: false

spring:
  application:
    name: eurekaSecurityServiceName
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      hikari:
        connection-timeout: 30000
        max-lifetime: 1800000
        max-pool-size: 15
        min-idle: 5
        connection-test-query: select 1
        pool-name: SunkHikariCP
      # 配置默认数据源
      primary: primary
      datasource:
        # 数据源-1，名称为 primary
        primary:
          username: software_db_username
          password: software_db_password
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://nms_domain:mysql_port/security_dbname?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
        # 数据源-2，名称为 test
#        test:
#          username: software_db_username
#          password: 123456
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://127.0.0.1:3306/febs_test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  aop:
    proxy-target-class: true

  messages:
    encoding: utf-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: redis_domain
    port: redis_port
    password: 
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0
  mqtt:
    host: "tcp://mqtt_domain:mqtt_port"
    clientId: ${spring.application.name}
    topic: "/topic1"
    username: admin
    password: password
    timeout: 30
    keepAlive: 60

cron-task-time: '*/30 * * * * ?'

#mybatis plus 设置
mybatis-plus:
  type-aliases-package: com.sunkaisens.ibss.system.domain
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: ALWAYS

ibss:
  # 是否异步记录用户操作日志
  openAopLog: true
  shiro:
    # 后端免认证接口 url, 逗号后前后不要有空格或tab等。
#    anonUrl: /login,/logout/**,/regist,/user/check/**,/eureka/**,/log/share/**,/access-network/**
    anonUrl: /api/login,/api/logout/**,/api/regist,/api/user/check/**,/api/eureka/**,/api/log/share/**,/log/share/**,/api/access-network/**,/login

#,/api/oss-resource-service/**,/api/oss-alarm-service/**
#,/antijam-1/**,/frequency-conversion-1/**,/antenna-1/**,/clock-1/**,/emergency-1/**,/antijam-1/**,/trunked-1/**,/frequency-conversion-2/**,/antenna-2/**,/clock-2/**,/emergency-2/**,/antijam-2/**,/trunked-2/**,/frequency-conversion-3/**,/antenna-3/**,/clock-3/**,/emergency-3/**,/antijam-3/**,/trunked-3/**
    # token有效期，单位秒
    jwtTimeOut: 2592000
    # 更新令牌时间检查配置，10分钟刷新一次     单位 ：秒
    refreshCheckTime: 600
  #ip转化为地域  
  ip2region:
    enabled: false
  # 单次最大批量入库数量
  max:
    batch:
      insert:
        num: 1000
swagger:
  enable: true  

eureka: 
  enabled: true
  client: 
    service-url: 
      defaultZone: http://eureka_domain:micro_port1/eureka,http://eureka_domain:micro_port2/eureka
  instance:
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true 
  
zuul:
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken 
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
  prefix: /api
  ignored-services: "*"
  strip-prefix: false
  routes:
    user:
      serviceId: eurekaUserServiceName
      path: /eurekaUserServiceName/**
    alarm:
      serviceId: eurekaAlarmServiceName
      path: /eurekaAlarmServiceName/**
    resource:
      serviceId: eurekaResourceServiceName
      path: /eurekaResourceServiceName/**
    statistic:
      serviceId: eurekaStatisticServiceName
      path: /eurekaStatisticServiceName/**
    gmapsystem:
      serviceId: aj03-gmapsystem-service 
      path: /aj03-gmapsystem-service/**
    kubernetes: 
      serviceId: aj03-kubernetes-service
      path: /aj03-kubernetes-service/**
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 10000
  ConnectTimeout: 10000
    
info:
  app.name: ${spring.application.name}
  company.name: www.sunkaisens.com

feign-service:
  log: eurekaStatisticServiceName
  organization: eurekaOrganizationServiceName
  alarm:  eurekaAlarmServiceName

logging:
  config: log4j2-spring.xml

