server:
  port: localPort
  servlet:
    context-path:

# omc 项目的路径 xsh 2020/1/11
spring:
  application:
    name: eurekaOrganizationServiceName
  datasource:
    dynamic:
      # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
      p6spy: true
      druid: #以下是全局默认值，可以全局更改
        initial-size: 0
        max-active: 30
        min-idle: 5
        max-wait: -1
        min-evictable-idle-time-millis: 30000
        max-evictable-idle-time-millis: 30000
        time-between-eviction-runs-millis: 0
        validation-query: select 1
        validation-query-timeout: -1
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        pool-prepared-statements: true
        max-open-prepared-statements: 100
        filters: stat,wall
        share-prepared-statements: true
      # 配置默认数据源
      primary: user
      datasource:
        # 数据源-1，名称为 primary
        user:
          username: softwareDbUsername
          password: softwareDbpassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localMysqlIp:3306/userDbName?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
        master:
          username: switchDbUsername
          password: switchDbPassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://switchIp:3306/hssDbName?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
        hss1:
          username: switchDbUsername
          password: switchDbPassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://switchIp:3306/hss1DbName?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
        hss2:
          username: switchDbUsername
          password: switchDbPassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://switchIp:3306/hss2DbName?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
        hss3:
          username: switchDbUsername
          password: switchDbPassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://switchIp:3306/hss3DbName?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
        hss4:
          username: switchDbUsername
          password: switchDbPassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://switchIp:3306/hss4DbName?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
        myomc:
          username: softwareDbUsername
          password: softwareDbpassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://switchIp:3306/myomcDbName?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
        cscfDb:
          username: switchDbUsername
          password: switchDbPassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://switchIp:3306/CSCF_DBDbName?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
        proxy:
          username: softwareDbUsername
          password: softwareDbpassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localMysqlIp:3306/hss_proxy_serviceDbName?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
        organization:
          username: softwareDbUsername
          password: softwareDbpassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localMysqlIp:3306/organizationDbName?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
        ocr:
          username: softwareDbUsername
          password: softwareDbpassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localMysqlIp:3306/ocrDbName?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
          # 呈现数据库 查询0203/WJHL项目的用户入网记录
        presence:
          username: softwareDbUsername
          password: softwareDbpassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://dispIp:3306/presenceDbName?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
        # imserver数据库 目前用于宽带项目/0203项目查询短信信息
        imserver:
          username: softwareDbUsername
          password: softwareDbpassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://dispIp:3306/imserverDbName?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
        # 资源管理数据库 目前仅用于AJU查询机动式接入记录
        resource:
          username: softwareDbUsername
          password: softwareDbpassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localMysqlIp:3306/resourceDbName?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
        # 性能统计数据库 目前仅用于WJHL项目的SNMP获取分组数据后存储及查看
        statistic:
          username: softwareDbUsername
          password: softwareDbpassword
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localMysqlIp:3306/statisticDbName?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull

  aop:
    proxy-target-class: true

  messages:
    basename: i18n/messages
    encoding: utf-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: redisIp
    port: redisPort
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0

  # 本地MQTT连接信息
  mqtt-local:
    enabled: true
    url: tcp://emqttIp:emqttPort
    clientId: ${spring.application.name}-${server.port}
    topic: Presence/Register/#
    topic-send: /1808-user-to-front
    username: admin
    password: password
    timeout: 30
    keepAlive: 60
  # 上级MQTT连接信息
  mqtt-boss:
    enabled: false
    url: tcp://superiorEmqttIp:superiorEmqttPort
    clientId: ${spring.application.name}-${server.port}-Subordinate
    topic: down/user/swoon,down/user/restore,down/user/destroy,down/user/normal
    timeout: 30
    keepAlive: 60
  mqtt-statistic:
    enabled: true
    url: tcp://emqttIp:emqttPort
    clientId: Statistic@Chris_dev
    topic: /raw_alarm/#,/raw_alarm1/#,/gate_way_change
    username: admin
    password: password
    timeout: 30
    keepAlive: 60

feign:
  hystrix:
    enabled: true


#mybatis plus 设置
mybatis-plus:
  type-aliases-package: com.sunkaisens.ibss.system.domain,com.sunkaisens.ibss.user.model
  #配置要扫描的Xml的文件 即sql文件
  mapper-locations: classpath:mapper/*/*.xml,classpath:mapper/*/*/*.xml,classpath:mapper/*/*/*/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    # 关闭 mybatis-plus的 banner
    banner: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

ibss:
  # 是否异步记录用户操作日志
  openAopLog: true
  openAopLogGet: false
  shiro:
    # 后端免认证接口 url
    anonUrl: /login,/logout/**,/regist,/user/check/**,/hss/share/**
    # token有效期，2个小时     两个小时如果不操作 会退出。单位 秒
    jwtTimeOut: 7200
    # 更新令牌时间检查配置，10分钟刷新一次     单位 ：秒
    refreshCheckTime: 600
  #ip转化为地域
  ip2region:
    enabled: false
  # 单次最大批量入库数量
  max:
    batch:
      # 单次最大新增数量
      insert-num: 1000
      # 单次最大删除数量
      delete-num: 1000
  # RestTemplate的超时配置
  rest-http:
    # 连接超时时间：单位 毫秒
    connect-timeout: 480000
    # 读取超时时间：单位 毫秒
    read-timeout: 360000

swagger:
  enable: true

info:
  app.name: ${spring.application.name}
  company.name: www.sunkaisense.com
#canal 配置
ali:
  canal:
    flag: false
    addr: 127.0.0.1
    port: 11111
    #      注意：带特殊字符的配置文件必须加双引号，否则会解析有误
    tablesubscribe: "ocr\\..*"
    user: root
    password: root
    hostName: statistic

iscc:
  user-group:
    enabled: false
    ip: dispIp
    port: groupPort
    groupType: public-group
    assertedIdentity: sip:administrator@test.com
  organization-group:
    enabled: false
    ip: dispIp
    port: groupPort
    groupType: public-group
    assertedIdentity: sip:administrator@test.com
  # 缓存IMSI MDN STATUS
  user-cache:
    # 缓存项最大数量
    size: 100000
    # 缓存时间：天
    duration: 10
  organization-cache:
    # 缓存项最大数量
    size: 100
    # 缓存时间：天
    duration: 10
  # 同步配置
  user-synchronized:
    # 是否向上级同步数据
    enabled: true
    # 上级用户管理IP
    ip: dataCenter.com
    # 上级用户管理PORT
    port: 7125
  organization-synchronized:
    # 本程序是否为顶级，此选项仅影响添加单位时的默认单位类型，true-分级单位和分域单位可选 false-分域单位
    data-center: false
    # 是否向上级同步
    enabled: true
    # 上级单位组织架构IP
    ip: datacenter.com
    # 上级单位组织架构PORT
    port: 7125
    # 向上级单位请求本单位的级单位信息
    level-cron: 0 0 0/2 * * ?
    # 向上级单位推送更新本单位的域单位信息
    domain-merge-cron: 0/30 * * * * ?
    # 向上级单位推送删除本单位的域单位信息
    domain-delete-cron: 0/30 * * * * ?
    # 本地单位ID
    unit-id: 4
    # 删除修改单位是否检测单位可否操作
    del-upt-check-unit: true
  local:
    # 定时处理未同步更新数据的CRON
    merge-cron: 0 0/3 * * * ?
    # 获取未同步数据的分页的每页数据量大小
    merge-page-size: 500
    # 定时处理未同步删除数据的CRON
    delete-cron: 0 0/3 * * * ?
    # 本程序部署的单位ID
    unitid: 4
    # 用户变更时是否使用该默认单位ID true:适用于2011 false:适用于0203
    # 使用默认单位ID-true，前端传输单位ID-false
    enable: true
    # 是否使用数据表再次对应优先级
    priority: false
  hss:
    # 批量添加操作是否开启线程执行
    batch-add-thread-switch: false
    # 批量删除操作是否开启线程执行
    batch-delete-thread-switch: false
    # TerminalInfo表写入开关
    terminalInfo-switch: true
    # EpcData和EpcTft表写入开关
    epc-switch: false
    # EpcData和EpcTft表写入类型 LTE-TD(5) LTE-CPE(13)
    epc-device-type: [ 5,13 ]
    # 批量添加用户时displayName字段截取规则
    batch-add-displayName-length: 8
    # 批量修改，忽略AUC鉴权参数修改的设备类型
    batch-update-ignore-auc-device-type: [ 7 ]
  net-policy:
    # 特殊网系规则配置（内容为：MDN前缀|网系ID|HSS代理模块ID）
    special-rules: [ "174|1|1","184|2|1" ]

#北向接口端口
aju-jds:
  port: 7350

auc-usim:
  enable: false
  url: http://10.0.30.104:8080/USIM_Manage30
  detect-cron: 0 */3 * * * ?
  # HSS-PROXY程序ID,AUC设备编号
  aucNoMap[1]: 202012254668
  aucNoMap[2]: 202012254662
  aucNoMap[3]: 202012254663
  aucNoMap[4]: 202012254664

# oam配置ip和port 以及网元ID和实例ID
oam:
  # 主库
  master:
    addr: hss.test.com:6124
    ne-inst: 10-1
    sub-1:
      addr: hss.test.com:6124
      ne-inst: 257-1
    sub-2:
      addr: 172.16.0.28:6126
      ne-inst: 259-3
    sub-3:
      addr: 172.16.0.3:6127
      ne-inst: 260-4
    sub-4:
      addr: 172.16.0.4:6128
      ne-inst: 261-5
  # 备库
  slave:
    # 是否开启备库
    switch: false
    addr: 172.16.1.0:6129
    ne-inst: 262-6
    sub-1:
      addr: 172.16.1.1:6130
      ne-inst: 263-7
    sub-2:
      addr: 172.16.1.2:6131
      ne-inst: 267-8
    sub-3:
      addr: 172.16.1.3:6132
      ne-inst: 265-9
    sub-4:
      addr: 172.16.1.4:6133
      ne-inst: 266-10


group:
  ipaddr: dispIp
  port: groupPort

# oam消息超时设置
udp:
  # 发送oam的UDP消息的延时时间(ms)
  sendDelay: 50
  # 发送oam的UDP消息的超时时间(s)
  timeout: 5

# 本地ip port  user管理项目的数据 xsh 2019/11/26
omc:
  ipaddr: nmsIp
  port: omcPort
  # 是否开启HSS分库
  hss-fk-switch: false
  # HSS分库数量
  hss-fk-count: 1
  # 批量操作数据库的每组数据量
  batch-seg: 100
  # TerminalInfo表写入开关
  terminalInfo-switch: true
  # EpcData和EpcTft表写入开关
  epc-switch: false
  epc-device-type: [ 5,13 ]
  # Cscf表写入类型 DISP(8) IMS(12)
  cscf-device-type: [ 8,12 ]
  # 网系策略的UDP消息开关
  net-policy-switch: false
  #流文件路径
  bear-qos-tft-file-path: /home/sun-nms/backend/oss/sun-nms-hss-proxy-service-2.0.0-SNAPSHOT/temp/
  bear-qos-tft-file-name: BearQoSTFT.info
  #流文件开关
  bear-qos-tft-file-switch: false
  # 批量修改，忽略AUC鉴权参数修改的设备类型
  batch-update-ignore-auc-device-type: [ 7 ]
  # 网间互联numOfVM开关，子网
  numOfVM-switch: false
# 发送到北向接口   xsh 2020/8/6
north:
  switchControl: false
  ip: nmsIp
  port: northInterfacePort
  timeout: 3

ftp:
  ip: nmsIp
  port: ftpPort
  username: ftpUsername
  password: ftpPassword

ribbon:
  eureka:
    enabled: true

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://microIp:microPort1/eureka/,http://microIp:microPort2/eureka/
  instance:
   # ip-address: 120.2.0.234
    instance-id: ${spring.application.name}-${server.port}
    prefer-ip-address: true     #访问路径可以显示IP地址

feign-service:
  log: eurekaSecurityServiceName
  organization: eurekaOrganizationServiceName
  resource: eurekaResourceServiceName
  gmap: nms-gmapsystem-service
  appear: https://dispIp:dispatcherPort/register/status

logging:
  config: classpath:log4j2-spring.xml

iscc-statistic:
  local:
    # 向上传输数据同步开关
    push-job-switch: false
    # 是否向上级传输数据 是-true 否-false
    upload-switch: false
    # 定时处理未同步更新数据的CRON
    push-cron: 0/5 * * * * ?
    # 获取下级数据传输数据开关
    get-job-switch: false
    # 获取下级数据传输数据的CRON
    get-cron: 0/5 * * * * ?
    # 过滤跨VCS开关
    filter-cross-vcs-switch: false

# 自动创建数据表
ocr-table-create:
  enable: true
  # 创建表的的CRON
  cron: 0 0 0/23 * * ?
  # 采集OCR数据库同步性能统计数据(采集任务)
  statistic-enable: true
  # 采集任务的CRON
  statistic-cron: 0 0/15 * * * ?

# 语音呼叫原因值
voice:
  # 无效原因值
  invalid: [ 1,2 ]
  # 成功原因值
  success: [ 0,16,7,18,21 ]
  # 外线网关IP
  out-line-ip: [ '172.46.17.74' ]
  # 网络类型判断，0-2/3G 1-4G
  net-type:
    0: [ '192.1.1.155:9122','192.1.1.155:9132' ]
    1: [ '192.1.1.64:9904','192.1.1.64:9907' ]

#ftp配置
ftp-statistic:
  ip: nmsIp
  port: ftpPort
  username: uftp
  password: sunkaisens@123
  # 本地ftp路径（下级向上级传输的数据）
  path: /var/ftp
  # 本地temp路径（临时存储向上传输的数据）
  temp-path: /var/ftp/local

snmp:
  # 是否开启snmp获取分组流量逻辑
  flag: false
  # 本机IP
  localAddress: 192.168.1.101
  # 单位 秒
  period: 60
  # 天通网系对应交换机IP及网口
  dataGateWayIp[1]: 192.168.1.31
  netPort[1]: 1,2,3,4
  nets[1]: 天通移动通信网
  # FDMA网系对应换机IP及网口
  dataGateWayIp[3]: 192.168.1.31
  netPort[3]: 5,6,7,8
  nets[3]: FDMA综合业务网
  # FDMA网系对应换机IP及网口
  dataGateWayIp[4]: 192.168.1.31
  netPort[4]: 9,10,11,12
  nets[4]: TDMA综合业务网
  # FDMA网系对应换机IP及网口
  dataGateWayIp[5]: 192.168.1.31
  netPort[5]: 13,14,15,16
  nets[5]: TDMA综合业务网及升级
  # FDMA网系对应换机IP及网口
  dataGateWayIp[10]: 192.168.1.31
  netPort[10]: 17,18,19,20
  nets[10]: 网间互联SIP
  # FDMA网系对应换机IP及网口
  dataGateWayIp[11]: 192.168.1.31
  netPort[11]: 21,22,23,24
  nets[11]: 网间互联固话
  # FDMA网系对应换机IP及网口
  dataGateWayIp[12]: 192.168.1.31
  netPort[12]: 25,26,27,28
  nets[12]: UHF战术/手持通信网
  # FDMA网系对应换机IP及网口
  dataGateWayIp[13]: 192.168.1.31
  netPort[13]: 29,30,31,32
  nets[13]: UHF频段通信网

